sudo: true
language: c
services: docker
addons:
  hosts:
    - mariadb.example.com
  homebrew:
    packages:
      - openssl
      - libiodbc
      - mariadb

before_install:
  - chmod +x .travis/script.sh
  - chmod +x .travis/osx.sh
  - chmod +x .travis/gen-ssl.sh
  - chmod +x .travis/build/build.sh
  - chmod +x .travis/build/docker-entrypoint.sh
  - chmod 777 .travis/build/
  - export PROJ_PATH=`pwd`
  - export ENTRYPOINT=$PROJ_PATH/.travis/sql
  - mkdir tmp
  - .travis/gen-ssl.sh mariadb.example.com tmp
  - export SSLCERT=$PROJ_PATH/tmp
  - export CONNECTOR_C_VERSION=v_2.3.3

matrix:
  allow_failures:
    - os: linux
      env: DB=mariadb:10.2 PACKET=8M MAXSCALE_VERSION=2.1.8
    - os: linux
      env: DB=mysql:5.5
    - os: linux
      env: DB=mysql:5.6
    - os: linux
      env: DB=mysql:5.7
  include:
    - os: linux
      env: DB=build
    - os: linux
      env: DB=mariadb:5.5
    - os: linux
      env: DB=mariadb:10.0
    - os: linux
      env: DB=mariadb:10.1
    - os: linux
      env: DB=mariadb:10.2
    - os: linux
      compiler: gcc
      env: DB=mariadb:10.3
    - os: linux
      compiler: clang
      env: DB=mariadb:10.3
    - os: osx
      compiler: clang
      env: DB=mariadb:10.3
    - os: linux
      env: DB=mariadb:10.2 PACKET=8M MAXSCALE_VERSION=2.1.8
    - os: linux
      env: DB=mysql:5.5
    - os: linux
      env: DB=mysql:5.6
    - os: linux
      env: DB=mysql:5.7

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$DB" = "build" ] ; then .travis/build/build.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$DB" = "build" ] ; then docker build -t build:latest --label build .travis/build/; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] ; then .travis/script.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then .travis/osx.sh; fi
